extend: 'beet-config.yaml'
id: lavaflow
name: Lavaflow
description: Overhauled Nether with lava rivers and more
require:
- beet.contrib.copy_files
data_pack:
  load:
  - "."
  - 'public'
  name: '{{project_id}}'
  pack_format: 71

pipeline:
- src.snowcapped
- src.handleBiomes
- src.generateDfs
- src.generateSurfaceRules

output: build

meta:
  copy_files:
    data_pack:
      README.md: public/README.md
      data/c/structure_icons.json: data/c/structure_icons.json
      assets/lavaflow/lang: assets/lavaflow/lang
      LICENSE.txt: LICENSE.txt
      AGPL.txt: AGPL.txt
