minecraft: 1.21
version: 0.5.2
author: jacobsjo
meta:
  modded:
    fabric: true
    quilt: false
    neoforge: true
    mcforge: true
    name: '{{project_id}}_{{project_version}}'
    
    group: eu.jacobsjo
    min_minecraft_version: 1.21.5
    max_minecraft_version: 1.21.7
    license: AGPL-3.0-or-later
    contact:
      homepage: https://modrinth.com/datapack/lavaflow
      issues: https://github.com/jacobsjo/lavaflow/issues
  zip:
    name: '{{project_id}}_{{project_version}}'
    