extend: 'beet-base.yaml'
output: build
pipeline:
- beet.contrib.minify_json
- plugins.modded
- plugins.githubOutput
- plugins.smithed_dialog
- beet.contrib.output

data_pack:
  zipped: true
  name: '{{project_id}}_{{project_version}}'