extend: 'beet.yaml'
output: build
pipeline:
- beet.contrib.minify_json
- src.modded
- src.githubOutput
- beet.contrib.output
- broadcast: compat/*/
  extend: beet.yaml
  data_pack:
    zipped: true
  output: ../../build/compat/
  pipeline:
  - src.modded
  - beet.contrib.output
  - src.zip
  - beet.contrib.clear
  meta:
    output:
      directory: ../../build/compat/

data_pack:
  zipped: true
  name: '{{project_id}}_{{project_version}}'