extend: 'beet-config.yaml'
id: lavaflow
name: Lavaflow
description: Overhauled Nether with lava rivers and more
require:
- beet.contrib.copy_files
data_pack:
  load:
  - "src"
  name: '{{project_id}}'
  pack_format: 71

pipeline:
- plugins.snowcapped
- plugins.handleBiomes
- plugins.generateDfs
- plugins.generateSurfaceRules

output: build

meta:
  copy_files:
    data_pack:
      data/c/structure_icons.json: src/data/c/structure_icons.json
      assets/lavaflow/lang: src/assets/lavaflow/lang
      LICENSE.txt: LICENSE.txt
      AGPL.txt: AGPL.txt
